### PR TITLE
commiting Jenniline Ebai's part of the work webapp login done with Re…

### PR DESCRIPTION
**Pull request by Jenniline**
…actjs
1st Pull Jenniline Ebai's part of the work (SIGN IN MODULE). I built the Frontend for the web part of the SIGN IN module done using React js

### CODE REVIEW

**Comment by usmailaabdoul** [comment]
i don't understand isn't Registration module (login and register ) for our group, what module are u working on

**Comment by xurror** [comment]
Can you explain what changes are done here?

**Comment by achilep** [comment]
hello @usmailaabdoul you are right

**Comment by Jenniline** [comment]
@usmailaabdoul I am working on Profile module. Read the description well.

**Comment by Jenniline** [comment]
@xurror I have pushed the code for the web part of the profile mode. My code makes the following changes.
It is for the Front end of the web part of our project. 

- It is built with React js

1. A user can Sign in with user details and Personal details
2. After login in the information used to log in can be displayed 
3. A user can update the information if he wishes to by clicking the 'update'  button and then 
4. The user can sign out.

**Comment by usmailaabdoul** [comment]
u are wasting time concentrating on the wrong things 
my group already handles Registration and Login 
u were just supposed to ask us the fields we ask users to enter so that u can display that information in the profile page instead of creating another login ?? or better still u could just assume information after when merging we could change that

**Comment by Jenniline** [comment]
@usmailaabdoul ok Thanks

**Comment by xurror** [comment]
I think my main concern here is that the files you have pushed are unreadable.

**Pull request closed without merging**
